-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidates
(
    users_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    nationiality_id character varying(11) NOT NULL,
    birthdate date NOT NULL,
    PRIMARY KEY (users_id)
);

CREATE TABLE public.employees
(
    users_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    PRIMARY KEY (users_id)
);

CREATE TABLE public.employers
(
    users_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_address character varying(100) NOT NULL,
    phone_number character varying(11) NOT NULL,
    is_activated bit(1) NOT NULL,
    PRIMARY KEY (users_id)
);

CREATE TABLE public.employers_activation_codes
(
    id integer NOT NULL,
    employer_user_id integer NOT NULL,
    activation_code character varying(20) NOT NULL,
    is_confirmed bit(1) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers_activation_employees
(
    id integer NOT NULL,
    employer_user_id integer NOT NULL,
    confirmed_employee_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL,
    "position" character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.candidates (users_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (users_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employees (users_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (users_id)
    REFERENCES public.employers_activation_employees (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (users_id)
    REFERENCES public.employers_activation_codes (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (users_id)
    REFERENCES public.employers_activation_employees (id)
    NOT VALID;

END;